programs:
  libreoffice:
    versions:
      - "7.5.4"
      - "7.6.0"
  git:
    versions:
      - "2.41.0"
      - "2.42.0"
  pycharm:
    versions:
      - "2025.2"
      - "2025.3"
  vlc:
    versions:
      - "3.0.18"
      - "4.0.0"

# Выбираем что устанавливать и какую версию
install_programs:
  libreoffice: "7.6.0"
  git: "2.42.0"
  pycharm: "2025.3"
  vlc: "4.0.0"
